"""
Pilot Program API

POST /api/v1/pilot/invite/generate   — admin generates invite codes
GET  /api/v1/pilot/invite/validate   — validate invite code before registration
POST /api/v1/pilot/invite/use        — mark invite as used after registration
GET  /api/v1/pilot/invites           — admin: list all invites + usage stats
DELETE /api/v1/pilot/invite/{id}     — admin: revoke an invite

POST /api/v1/pilot/feedback          — submit feedback (auth optional)
GET  /api/v1/pilot/feedback          — admin: list all feedback
GET  /api/v1/pilot/feedback/summary  — admin: NPS + rating aggregates
GET  /api/v1/pilot/status            — public: pilot program status (slots used/total)
"""
from __future__ import annotations

import logging
import secrets
from datetime import datetime, timezone, timedelta
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.pilot import PilotInvite, UserFeedback
from app.models.user import User
from app.api.auth import get_current_user
from app.config import get_settings

router = APIRouter()
logger = logging.getLogger(__name__)

PILOT_MAX_USERS = 5  # overrideable via env
INVITE_EXPIRE_DAYS = 30


# ── Pydantic schemas ──────────────────────────────────────────────────────────

class GenerateInviteRequest(BaseModel):
    email: str | None = None
    note: str | None = None
    count: int = Field(default=1, ge=1, le=20)
    expire_days: int = Field(default=INVITE_EXPIRE_DAYS, ge=1, le=365)


class FeedbackRequest(BaseModel):
    job_id: str | None = None
    nps_score: int | None = Field(default=None, ge=0, le=10)
    analysis_rating: int | None = Field(default=None, ge=1, le=5)
    accuracy_rating: int | None = Field(default=None, ge=1, le=5)
    usefulness_rating: int | None = Field(default=None, ge=1, le=5)
    speed_rating: int | None = Field(default=None, ge=1, le=5)
    comment: str | None = Field(default=None, max_length=2000)
    biggest_benefit: str | None = Field(default=None, max_length=1000)
    biggest_gap: str | None = Field(default=None, max_length=1000)
    page_context: str | None = Field(default=None, max_length=100)


def _require_admin(user: User) -> User:
    if user.role not in ("admin", "owner"):
        raise HTTPException(status_code=403, detail="Admin yetkisi gerekli.")
    return user


# ── Pilot status (public) ────────────────────────────────────────────────────

@router.get("/pilot/status")
async def pilot_status(db: AsyncSession = Depends(get_db)) -> dict[str, Any]:
    """Return current pilot program status — public endpoint."""
    settings = get_settings()
    max_users = getattr(settings, "pilot_max_users", PILOT_MAX_USERS)

    # Count active users (non-admin)
    result = await db.execute(
        select(func.count()).select_from(User).where(User.is_active == True)
    )
    total_users = result.scalar() or 0

    # Count unused invites
    inv_result = await db.execute(
        select(func.count()).select_from(PilotInvite).where(
            PilotInvite.used == False,
            (PilotInvite.expires_at == None) | (PilotInvite.expires_at > datetime.now(timezone.utc)),
        )
    )
    available_slots = inv_result.scalar() or 0

    return {
        "data": {
            "pilot_active": True,
            "max_users": max_users,
            "current_users": total_users,
            "slots_remaining": max(0, max_users - total_users),
            "available_invites": available_slots,
            "accepting_new_users": total_users < max_users,
        },
        "error": None,
    }


# ── Invite management (admin) ─────────────────────────────────────────────────

@router.post("/pilot/invite/generate", status_code=201)
async def generate_invites(
    body: GenerateInviteRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Admin: generate one or more invite codes."""
    _require_admin(current_user)

    expires = datetime.now(timezone.utc) + timedelta(days=body.expire_days)
    codes = []

    for _ in range(body.count):
        code = secrets.token_urlsafe(16)  # 22 chars, URL-safe
        invite = PilotInvite(
            code=code,
            email=body.email if body.count == 1 else None,
            note=body.note,
            expires_at=expires,
        )
        db.add(invite)
        codes.append({"code": code, "expires_at": expires.isoformat()})

    await db.commit()
    logger.info("Pilot: %d invite(s) generated by %s", body.count, current_user.email)

    return {"data": {"invites": codes, "count": len(codes)}, "error": None}


@router.get("/pilot/invite/validate")
async def validate_invite(
    code: str,
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Public: check if an invite code is valid."""
    result = await db.execute(
        select(PilotInvite).where(PilotInvite.code == code)
    )
    invite = result.scalar_one_or_none()

    if not invite:
        return {"data": {"valid": False, "reason": "Geçersiz davet kodu."}, "error": None}
    if invite.used:
        return {"data": {"valid": False, "reason": "Bu davet kodu zaten kullanılmış."}, "error": None}
    if invite.expires_at and invite.expires_at < datetime.now(timezone.utc):
        return {"data": {"valid": False, "reason": "Davet kodunun süresi dolmuş."}, "error": None}

    return {
        "data": {
            "valid": True,
            "invite_id": invite.id,
            "email": invite.email,
            "note": invite.note,
        },
        "error": None,
    }


@router.post("/pilot/invite/use")
async def use_invite(
    code: str,
    user_id: str,
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Mark an invite as used after successful registration."""
    result = await db.execute(
        select(PilotInvite).where(PilotInvite.code == code, PilotInvite.used == False)
    )
    invite = result.scalar_one_or_none()
    if not invite:
        raise HTTPException(400, detail="Geçersiz veya kullanılmış davet kodu.")

    invite.used = True
    invite.used_by_user_id = user_id
    invite.used_at = datetime.now(timezone.utc)
    await db.commit()
    return {"data": {"used": True}, "error": None}


@router.get("/pilot/invites")
async def list_invites(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Admin: list all invite codes with usage info."""
    _require_admin(current_user)
    result = await db.execute(
        select(PilotInvite).order_by(PilotInvite.created_at.desc())
    )
    invites = result.scalars().all()
    return {
        "data": [
            {
                "id": i.id,
                "code": i.code,
                "email": i.email,
                "note": i.note,
                "used": i.used,
                "used_by": i.used_by_user_id,
                "used_at": i.used_at.isoformat() if i.used_at else None,
                "expires_at": i.expires_at.isoformat() if i.expires_at else None,
                "created_at": i.created_at.isoformat(),
            }
            for i in invites
        ],
        "error": None,
    }


@router.delete("/pilot/invite/{invite_id}")
async def revoke_invite(
    invite_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Admin: revoke an unused invite."""
    _require_admin(current_user)
    invite = await db.get(PilotInvite, invite_id)
    if not invite:
        raise HTTPException(404, detail="Davet bulunamadı.")
    if invite.used:
        raise HTTPException(400, detail="Kullanılmış davet kodu iptal edilemez.")
    await db.delete(invite)
    await db.commit()
    return {"data": {"revoked": True}, "error": None}


# ── Feedback ──────────────────────────────────────────────────────────────────

@router.post("/pilot/feedback", status_code=201)
async def submit_feedback(
    body: FeedbackRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User | None = Depends(lambda: None),  # auth optional
) -> dict[str, Any]:
    """Submit post-analysis feedback. Auth optional — anonymous feedback allowed."""
    fb = UserFeedback(
        user_id=current_user.id if current_user else None,
        job_id=body.job_id,
        org_id=current_user.org_id if current_user else None,
        nps_score=body.nps_score,
        analysis_rating=body.analysis_rating,
        accuracy_rating=body.accuracy_rating,
        usefulness_rating=body.usefulness_rating,
        speed_rating=body.speed_rating,
        comment=body.comment,
        biggest_benefit=body.biggest_benefit,
        biggest_gap=body.biggest_gap,
        page_context=body.page_context,
    )
    db.add(fb)
    await db.commit()
    await db.refresh(fb)

    logger.info(
        "Feedback submitted: id=%s nps=%s rating=%s",
        fb.id, body.nps_score, body.analysis_rating,
    )

    return {"data": {"feedback_id": fb.id}, "error": None}


@router.get("/pilot/feedback")
async def list_feedback(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    limit: int = 50,
    offset: int = 0,
) -> dict[str, Any]:
    """Admin: list all feedback entries."""
    _require_admin(current_user)
    result = await db.execute(
        select(UserFeedback)
        .order_by(UserFeedback.created_at.desc())
        .limit(limit)
        .offset(offset)
    )
    entries = result.scalars().all()

    count_result = await db.execute(select(func.count()).select_from(UserFeedback))
    total = count_result.scalar() or 0

    return {
        "data": {
            "total": total,
            "entries": [
                {
                    "id": f.id,
                    "user_id": f.user_id,
                    "job_id": f.job_id,
                    "nps_score": f.nps_score,
                    "analysis_rating": f.analysis_rating,
                    "accuracy_rating": f.accuracy_rating,
                    "usefulness_rating": f.usefulness_rating,
                    "speed_rating": f.speed_rating,
                    "comment": f.comment,
                    "biggest_benefit": f.biggest_benefit,
                    "biggest_gap": f.biggest_gap,
                    "page_context": f.page_context,
                    "created_at": f.created_at.isoformat(),
                }
                for f in entries
            ],
        },
        "error": None,
    }


@router.get("/pilot/feedback/summary")
async def feedback_summary(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Admin: aggregate NPS + ratings summary."""
    _require_admin(current_user)

    result = await db.execute(select(UserFeedback))
    all_fb = result.scalars().all()

    if not all_fb:
        return {
            "data": {
                "total_responses": 0,
                "nps_score": None,
                "avg_analysis_rating": None,
                "avg_accuracy_rating": None,
                "avg_usefulness_rating": None,
                "avg_speed_rating": None,
                "promoters": 0,
                "passives": 0,
                "detractors": 0,
                "top_benefits": [],
                "top_gaps": [],
            },
            "error": None,
        }

    # NPS calculation
    nps_scores = [f.nps_score for f in all_fb if f.nps_score is not None]
    promoters  = sum(1 for s in nps_scores if s >= 9)
    passives   = sum(1 for s in nps_scores if 7 <= s <= 8)
    detractors = sum(1 for s in nps_scores if s <= 6)
    nps = round(((promoters - detractors) / len(nps_scores)) * 100) if nps_scores else None

    def _avg(values: list[int]) -> float | None:
        filtered = [v for v in values if v is not None]
        return round(sum(filtered) / len(filtered), 2) if filtered else None

    return {
        "data": {
            "total_responses": len(all_fb),
            "nps_score": nps,
            "avg_analysis_rating": _avg([f.analysis_rating for f in all_fb]),
            "avg_accuracy_rating": _avg([f.accuracy_rating for f in all_fb]),
            "avg_usefulness_rating": _avg([f.usefulness_rating for f in all_fb]),
            "avg_speed_rating": _avg([f.speed_rating for f in all_fb]),
            "promoters": promoters,
            "passives": passives,
            "detractors": detractors,
            "top_benefits": [
                f.biggest_benefit for f in all_fb
                if f.biggest_benefit
            ][:10],
            "top_gaps": [
                f.biggest_gap for f in all_fb
                if f.biggest_gap
            ][:10],
        },
        "error": None,
    }
